# SLF4J Simple Logger 配置
# 设置输出流为 System.out
org.slf4j.simpleLogger.logFile=System.out
# 显示日期时间
org.slf4j.simpleLogger.showDateTime=true
# 日期时间格式
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
# 显示线程名称
org.slf4j.simpleLogger.showThreadName=true
# 显示日志级别
org.slf4j.simpleLogger.showLogName=false
# 显示简短的类名
org.slf4j.simpleLogger.showShortLogName=true
# 默认日志级别
org.slf4j.simpleLogger.defaultLogLevel=info
